apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-acorn-prod
resources:
  - ../../base
namePrefix: prod-
nameSuffix: -prod

patches:
  - path: rollout-patch.yaml
  - path: ingress-patch.yaml
  - path: preview-ingress-patch.yaml

replacements:
  - source:
      kind: Service
      name: project-acorn-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: TraefikService
          name: project-acorn-traefik-weighted
        fieldPaths:
          - spec.weighted.services.[name=project-acorn-service].name
  
  - source:
      kind: Service
      name: project-acorn-preview-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: TraefikService
          name: project-acorn-traefik-weighted
        fieldPaths:
          - spec.weighted.services.[name=project-acorn-preview-service].name

images:
  - name: project-acorn-image
    newName: ghcr.io/donhamiltoniii/project-acorn
    newTag: latest