apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-acorn-prod
resources:
  - ../../base
namePrefix: prod-
nameSuffix: -prod
commonLabels:
  environment: prod
patchesStrategicMerge:
  - rollout-patch.yaml
  - ingress-patch.yaml
  - preview-ingress-patch.yaml
images:
  - name: project-acorn-image
    newName: ghcr.io/donhamiltoniii/project-acorn
    newTag: latest