apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-acorn-prod
resources:
  - ../../base
namePrefix: prod-
nameSuffix: -prod

patches:
  - path: rollout-patch.yaml
  - path: ingress-patch.yaml
  - path: preview-ingress-patch.yaml
  # Remove traefik-service-patch.yaml since we're using replacements

# Keep your existing replacements for TraefikService references
replacements:
  # Update the active service reference in TraefikService
  - source:
      kind: Service
      name: project-acorn-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: TraefikService
          name: project-acorn-traefik-weighted
        fieldPaths:
          - spec.weighted.services.[name=project-acorn-service].name
  
  # Update the preview service reference in TraefikService
  - source:
      kind: Service
      name: project-acorn-preview-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: TraefikService
          name: project-acorn-traefik-weighted
        fieldPaths:
          - spec.weighted.services.[name=project-acorn-preview-service].name

  # Fix Ingress Traefik annotation to reference correct TraefikService
  - source:
      kind: TraefikService
      name: project-acorn-traefik-weighted
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
          name: project-acorn-ingress
        fieldPaths:
          - metadata.annotations.[traefik.ingress.kubernetes.io/service.name]

images:
  - name: project-acorn-image
    newName: ghcr.io/donhamiltoniii/project-acorn
    newTag: latest