apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-acorn-prod
resources:
  - ../../base
namePrefix: prod-
nameSuffix: -prod
patches:
  - path: rollout-patch.yaml
  - path: ingress-patch.yaml
  - path: preview-ingress-patch.yaml
  - path: traefik-service-patch.yaml
images:
  - name: project-acorn-image
    newName: ghcr.io/donhamiltoniii/project-acorn
    newTag: latest