apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project-acorn
  namespace: project-acorn
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  template:
    spec:
      containers:
        - name: website
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: ENVIRONMENT
              value: "production"
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 600